package com.example.dinehero;

import android.content.Intent;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.view.MenuItem;
import android.widget.Toast;

import androidx.annotation.ColorInt;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.dinehero.databinding.ActivityMainBinding;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.android.material.navigation.NavigationBarView;

import java.util.ArrayList;

public class MainActivity2 extends AppCompatActivity {

    private RecyclerView products;
    private static ArrayList<Product> productsList = new ArrayList<>();
    private BottomNavigationView TNV;



     ActivityMainBinding binding;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        products = findViewById(R.id.Products);

        TNV = findViewById(R.id.topNavView);
        TNV.setItemActiveIndicatorEnabled(false);

        //Top Navigation View - Allows User to navigate through app.   Java File
        TNV.setOnItemSelectedListener(new NavigationBarView.OnItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                if (item.getItemId() == findViewById(R.id.btnDiscover).getId()) {

                    openMainActivity();
                } else if (item.getItemId() == findViewById(R.id.btnForYou).getId()) {
                    openForYouActivity();
                } else if (item.getItemId() == findViewById(R.id.btnFollowing).getId()) {
                    openProfileActivity();
                }
                else if (item.getItemId() == findViewById(R.id.btnSearch).getId()) {
                    openSearchActivity();
                }

                return false;
            }
        });







        if(ForYouActivity.getFirst()) {


            //Events are called Products. This code allows all events to be displayed in the Event Page

            productsList.add(new Product("End Puppy Mills: Stricter Animal Breeding Regulations", "Every year, thousands of dogs are bred in horrific conditions, subjected to neglect, malnutrition, and inhumane treatment in puppy mills. These facilities treat dogs like commodities, often cramming them into filthy cages with little to no veterinary care, resulting in severe health problems and emotional trauma for the animals. The puppies are often sold to pet stores or directly to consumers without proper background checks, continuing a cycle of neglect. We must act now to enforce stricter breeding laws and regulations that ensure breeders adhere to humane treatment standards. These laws should include mandatory inspections, licensing requirements, and penalties for violators. It’s time to protect the well-being of these vulnerable animals by putting an end to this cruel industry. By supporting this petition, you are standing up for responsible pet ownership, advocating for humane treatment, and helping to stop the cycle of suffering for countless dogs.", "Animal Cruelty", new User("Macy Kenner", "ihbshb@",R.drawable.women,32,4.2,"Entrepreneur by day, dreamer by night! Founder of a boutique marketing agency with a side hustle in spreading smiles and good vibes. Chicago born and raised, so you know I've got that Midwestern charm! Passionate about shaking up the status quo and making a positive impact. When I'm not hustling, you can find me exploring the city's hidden gems or binge-watching my favorite sitcoms.️ Firm believer in the power of community and lifting each other up. Let's chat about business, social change, or our latest Netflix obsessions! Oh, and did I mention I make killer homemade cookies? 405-567-9847",5), R.drawable.saddog,false,"63",2742,4,0));
            productsList.add(new Product("Ban Wild Animal Circuses: Protect Animals from Abuse","For decades, wild animals such as elephants, lions, and tigers have been forced to perform unnatural tricks for human entertainment, often subjected to abusive training methods involving whips, electric prods, and isolation. These intelligent, social animals are stripped of their dignity and kept in small, barren cages, enduring lives of misery in traveling circuses. This cruel practice has no place in a modern, compassionate society. Studies have shown that animals in captivity suffer from extreme stress, depression, and physical ailments. Many countries have already banned the use of wild animals in circuses, recognizing the inherent cruelty in their treatment. We must join this movement and demand that our government implement a nationwide ban on wild animal performances. Together, we can help create a future where entertainment is free from cruelty and where wild animals can live their lives in peace and freedom.","Animal Cruelty",new User("Jeff Sulk","qhdjskdn",R.drawable.men7,23,4.6,"Music aficionado with a groove for every beat and a melody for every mood. Whether I'm spinning vinyl at a local club or jamming out on my guitar at home, I'm always immersed in the rhythm of life. Proud audiophile with a collection that spans genres and decades. When I'm not lost in the world of music, you can find me exploring the city's vibrant music scene or seeking out the perfect cup of coffee to fuel my next jam session. Firm believer in the power of music to heal, inspire, and unite. Let's swap playlists, share concert stories, or maybe even start a band together! 405-875-7412",3), R.drawable.animalcicus,false,"68",43645,3,0));
            productsList.add(new Product("Ban the Sale of Cosmetics Tested on Animals","Millions of animals suffer and die each year in cruel and unnecessary cosmetic testing. Rabbits, mice, and other animals are subjected to painful experiments that often result in severe injury or death, all in the name of beauty products. Despite the availability of alternative testing methods that do not involve animals, many companies continue to rely on these outdated and inhumane practices. We must demand a ban on the sale of cosmetics tested on animals and push for cruelty-free standards in the beauty industry. By refusing to purchase products that rely on animal testing, we can encourage companies to adopt humane and ethical alternatives. Sign this petition to help end the suffering of animals in the cosmetic industry and promote cruelty-free beauty standards around the world.","Animal Cruelty",new User("Max Walter","qwerty123",R.drawable.men9,26,4.7, "Actor with a passion for embodying characters and bringing stories to life. Whether it's a riveting drama or a hilarious comedy, I'm always chasing the perfect performance. Immersed in the vibrant energy of the theater, I find inspiration in every stage I step onto. When I'm not rehearsing lines, you can find me exploring local cafes, attending live performances, or practicing yoga. Proud plant parent to Fern, the most graceful green companion you'll ever meet! Let's share acting tips or plan our next theater outing. 405-958-4100" ,6), R.drawable.cosonanimal,false,"32",325,5,15));
            productsList.add(new Product("Protect Endangered Species from Trophy Hunting", "Trophy hunting poses a significant threat to endangered species around the world, with wealthy hunters paying exorbitant fees to kill lions, elephants, rhinos, and other vulnerable animals for sport. These animals are already struggling to survive due to habitat loss, poaching, and climate change, and trophy hunting only accelerates their decline. The practice of killing endangered animals for trophies is not only unethical but also contributes to the extinction of some of the world’s most iconic species. We must call for an immediate ban on trophy hunting of endangered species and push for stronger international protections for wildlife. By signing this petition, you are standing up for the conservation of our planet’s most vulnerable animals and helping to preserve biodiversity for future generations. Let’s work together to end trophy hunting and protect endangered species from extinction.","Animal Cruelty",new User("Avery Medows","asedrfrf",R.drawable.women4,27,4.3,"Creative soul with a passion for expressing myself through art in all its forms. Whether I'm painting on canvas, crafting pottery, or strumming chords on my guitar, I'm always seeking new ways to bring beauty into the world. Proud dreamer with a love for exploring the depths of imagination and pushing the boundaries of creativity. When I'm not lost in my creative pursuits, you can find me exploring nature's wonders, indulging in a good book, or savoring a cup of coffee at a cozy café. Firm believer in the power of art to inspire, heal, and connect us all. Let's swap artistic inspirations, share our favorite books, or maybe even collaborate on a project together! 405-847-8569",4), R.drawable.trophiehunting,false,"79",14246,6,0));
            productsList.add(new Product("Prohibit Factory Farming Practices That Harm Animals","Factory farms, which raise livestock in concentrated animal feeding operations (CAFOs), subject animals to cramped, filthy conditions and often deprive them of natural behaviors. These practices not only cause immense suffering for the animals but also contribute to environmental degradation through pollution and deforestation. Factory farming is a major driver of greenhouse gas emissions, deforestation, and water contamination, making it both a humanitarian and environmental issue. We must demand legislation that prohibits the most harmful factory farming practices, including extreme confinement, the overuse of antibiotics, and inhumane slaughter methods. Additionally, stricter environmental regulations must be put in place to limit the ecological impact of factory farms. By signing this petition, you are taking a stand against animal cruelty and environmental destruction, advocating for more sustainable and ethical farming practices that protect both animals and our planet.","Animal Cruelty",new User("Piper Woodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors..️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-852-9684",12), R.drawable.factoryfarm,false,"18",6412,5,5));
            productsList.add(new Product("Protect Endangered Species from Habitat Loss","Habitat loss due to deforestation, urban development, and agriculture is one of the leading causes of species extinction. As natural habitats are destroyed, endangered species are left with nowhere to live, pushing them closer to extinction. Protecting critical habitats is essential for the survival of species such as elephants, tigers, and orangutans, which play vital roles in maintaining healthy ecosystems. We must demand stronger protections for endangered species and their habitats, including the creation of more wildlife reserves and stricter enforcement of anti-poaching laws. This includes ensuring that development projects do not encroach on critical habitats and supporting reforestation efforts to restore damaged ecosystems. By signing this petition, you are advocating for the protection of biodiversity and the survival of endangered species. Let’s work together to preserve the natural world and prevent further extinctions.","Animal Cruelty",new User("Ethan Allen","zxcvbn",R.drawable.men3,47,4.1,"Creative soul with a flair for design and a knack for DIY projects.️ Whether it's refurbishing old furniture or sketching out new home decor ideas, I'm always on a mission to bring beauty into everyday life. Proud small-town guy with big city dreams. When I'm not busy crafting or brainstorming my next project, you can catch me sipping on artisanal coffee or browsing through flea markets in search of hidden treasures. Thrilled to be a part of the maker community and constantly inspired by fellow artists and craftsmen. Let's chat about all things design, from mid-century modern to rustic chic! 405-878-9986",4), R.drawable.habitatloss,false,"11",31245,6,0));
            productsList.add(new Product("Pass Anti-Hoarding Laws to Protect Animals from Neglect","Animal hoarding is a form of neglect where individuals keep large numbers of animals in unsanitary and overcrowded conditions, often without the means to provide proper care. Hoarded animals suffer from malnutrition, untreated medical conditions, and extreme stress, while their caretakers may be unaware of the harm they are causing. Stronger anti-hoarding laws are needed to protect animals from this form of abuse. We must demand the passage of anti-hoarding laws that provide clear guidelines for the number of animals individuals can keep and require regular inspections for large collections of animals. This includes providing resources for animal rescue and rehabilitation in cases of hoarding. By signing this petition, you are standing up for the protection of animals from neglect and advocating for stronger legal protections. Let’s work together to end animal hoarding and ensure that every animal receives the care and love they deserve.","Animal Cruelty",new User("Piper Woodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors.️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-785-2514",12), R.drawable.hoarding,false,"29",16845,5,0));


            productsList.add(new Product("Slow Down, Save Lives: Install Speed Cameras in School Zones","Every day, children’s lives are endangered by reckless speeding through school zones, where they should feel the safest. Despite clearly marked signs and flashing lights, too many drivers ignore speed limits, putting our children and communities at risk. Studies have shown that speed cameras are highly effective in reducing speeding and preventing accidents. By installing these cameras, we can take decisive action to protect our kids, ensure drivers respect the law, and create a safer environment around our schools.We cannot wait for tragedy to strike before we act. Speed cameras provide accountability, discouraging dangerous driving behaviors and empowering law enforcement to hold violators accountable.Let’s make our voices heard. Demand the installation of speed cameras in school zones to ensure our children can walk, bike, and play safely. Together, we can prevent avoidable tragedies and create safer communities for everyone.","Safety",new User("Trent Williams","asdfghjkl;",R.drawable.men2,26,4.5,"Musician with a day job as a software engineer - talk about a double life! Strumming chords by night, coding by day. Proud West Coaster soaking up the sun and surfing whenever I can catch a wave. When I'm not lost in lines of code or jamming with my band, you can find me exploring the great outdoors or chilling with my furry best friend, Max. Passionate about technology, music, and finding the perfect taco spot. Let's swap Spotify playlists or geek out over the latest tech trends! 405-875-9632",2), R.drawable.schoolzone, false, "77",3874,10,5));
            productsList.add(new Product("Ban the Use of Solitary Confinement for Juveniles","Solitary confinement is a cruel and inhumane practice that has been shown to cause severe psychological harm, especially when used on juveniles. Despite this, many states continue to place young people in solitary confinement, often for extended periods, leading to long-term mental health issues and developmental delays. No child should be subjected to this form of punishment, which is widely regarded as a form of torture by mental health professionals. We must push for a nationwide ban on the use of solitary confinement for juveniles and advocate for more humane and rehabilitative approaches to juvenile justice. By eliminating this harmful practice, we can protect young people from unnecessary trauma and ensure that they receive the support and guidance they need to reintegrate into society. Let’s stand together to demand an end to juvenile solitary confinement and promote a justice system that prioritizes the well-being of all young people.","Safety",new User("Jason Blake","volunteer123",R.drawable.men14,43,4.9,"Environmentalist with a passion for protecting our planet and advocating for sustainability. Whether it's organizing a beach cleanup or planting trees, I'm always chasing the perfect eco-friendly solution. Rooted in a deep love for nature, I find inspiration in the beauty of our natural world. When I'm not leading environmental initiatives, you can find me tending to my garden, exploring local farmer's markets, or practicing mindfulness in the great outdoors. Proud dog parent to Barkley, the most adventurous eco-warrior you'll ever meet! Let's share green living tips or plan our next volunteer project. 405-999-8659",4), R.drawable.teenjail,false,"35",39234,40000,0));
            productsList.add(new Product("Mandate Stricter Regulations on Air Pollution","Air pollution poses a significant threat to public health, contributing to respiratory diseases, heart conditions, and premature deaths. Industrial emissions, vehicle exhaust, and other pollutants contaminate the air we breathe, particularly in urban areas and low-income communities. While some regulations exist to limit air pollution, they are often insufficient or poorly enforced, leaving millions of people vulnerable to its harmful effects. We must demand stricter air pollution regulations at the federal, state, and local levels to protect public health. This includes reducing emissions from industrial facilities, investing in clean energy alternatives, and promoting public transportation to reduce vehicle pollution. By signing this petition, you are standing up for the right to clean air and supporting policies that prioritize the health and well-being of all communities. Let’s work together to create a future where everyone can breathe clean, healthy air.","Safety",new User("Junior Yombi","olmkubn",R.drawable.men5,22,4.9,"Artist with a passion for painting the world in vibrant colors.️ Whether I'm creating captivating portraits or experimenting with abstract forms, I'm always on a journey to express myself through art. Proud dreamer with a vision for a brighter, more beautiful world. When I'm not lost in my creative process, you can find me exploring nature's wonders or jamming out to my favorite tunes on the guitar. Firm believer in the power of positivity and spreading love through my artwork. Let's swap artistic inspirations or embark on a spontaneous adventure to find the perfect painting spot! 405-864-9854",11), R.drawable.airpollution,false,"59",4,5,0));
            productsList.add(new Product("Ensure Safe Drinking Water for All Communities","Safe drinking water is a fundamental human right, yet many communities across the country still suffer from contaminated water supplies. From lead in aging pipes to chemical runoff from industrial farms, water contamination disproportionately affects low-income and rural communities, leading to long-term health issues and even death. Everyone deserves access to clean, safe drinking water, regardless of where they live. We must demand comprehensive action to upgrade outdated water infrastructure, address contamination sources, and ensure that all communities have access to safe drinking water. This includes holding corporations accountable for pollution, investing in water treatment facilities, and providing emergency relief for communities in crisis. By signing this petition, you are standing up for the health and safety of vulnerable populations and advocating for a future where no one has to live without access to clean water.","Safety",new User("Lanee Philip","yuioplkjhg",R.drawable.women3,52,5.0,"Photography enthusiast with a passion for capturing life's fleeting moments. Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. Proud explorer with a love for travel and a desire to see every corner of the globe. When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-965-8945",2), R.drawable.dirtywater,false,"51",54005,4,7));
            productsList.add(new Product("Make Child Car Seats Mandatory on Public Transportation","Every year, countless children are injured in accidents involving public transportation, yet there are no laws mandating the use of child safety seats on buses, shuttles, or rideshare services. While personal vehicles are required to have car seats for young children, the same safety standards do not apply to public transport, leaving young passengers vulnerable to injury or death in the event of a crash. It is time to close this dangerous gap in child safety laws. By mandating the use of child car seats on all forms of public transportation, we can ensure that children are protected no matter how they travel. Public transit companies, rideshare services, and even school buses should be required to provide appropriate seating for young passengers or allow parents to bring their own seats. Children’s safety should never be compromised, and it is our responsibility to protect them from harm. By signing this petition, you are advocating for a simple yet life-saving measure that will make public transportation safer for children across the country.","Safety",new User("Peter Rick","poiuhnm",R.drawable.men8,38,4.7,"Tech enthusiast with a passion for innovation and a knack for problem-solving.  Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology.️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-2358-9865",2), R.drawable.carseattransit,false,"23",28741,7,10));
            productsList.add(new Product("Ban the Use of Harmful Chemicals in Everyday Products","Harmful chemicals, such as BPA, phthalates, and formaldehyde, are found in many everyday products, from cosmetics and cleaning supplies to food packaging. These chemicals have been linked to a range of health issues, including cancer, reproductive problems, and developmental disorders. Despite the known risks, many companies continue to use these dangerous substances in their products, putting consumers at risk. We must demand that the government ban the use of harmful chemicals in everyday products and require companies to adopt safer, non-toxic alternatives. By signing this petition, you are advocating for stronger consumer protection laws and the right to live in a world free from harmful substances. Let’s work together to protect public health and hold companies accountable for the safety of their products.", "Safety",new User("Zack Turner","kjhgfds",R.drawable.men4,25,3.9,"Gamer by night, tech wizard by day! Whether I'm diving into the latest RPG or coding up a storm, I'm always in my element when I'm immersed in the world of technology. Proud nerd with a passion for all things sci-fi and fantasy. When I'm not conquering virtual realms or tinkering with gadgets, you can find me exploring the great outdoors or whipping up some mean BBQ on the grill. Firm believer in the power of friendship and the importance of always having a backup plan. Let's geek out over our favorite games or debate the merits of Star Trek vs. Star Wars! 405-8532-3245",6), R.drawable.harmfulchem,false,"48",46324,6,7));


            productsList.add(new Product("End Employment Discrimination Against Criminal Records","People with criminal records face significant barriers to finding employment, even after they have served their time and paid their debt to society. Many employers use criminal history as a blanket disqualification, denying individuals the opportunity to reintegrate into the workforce and rebuild their lives. This practice disproportionately affects people of color and low-income communities, perpetuating cycles of poverty and recidivism. We must demand the passage of “Ban the Box” legislation, which prohibits employers from asking about criminal history on job applications and allows individuals to be judged based on their qualifications rather than their past. By providing a fair chance for people with criminal records to secure employment, we can reduce recidivism, strengthen our communities, and give individuals the opportunity to contribute positively to society. Let’s stand together to end this form of discrimination and create a more just and equitable workforce.","Discrimination",new User("Ethan Allen","zxcvbn",R.drawable.men3,47,4.1,"Creative soul with a flair for design and a knack for DIY projects.️ Whether it's refurbishing old furniture or sketching out new home decor ideas, I'm always on a mission to bring beauty into everyday life. Proud small-town guy with big city dreams. When I'm not busy crafting or brainstorming my next project, you can catch me sipping on artisanal coffee or browsing through flea markets in search of hidden treasures. Thrilled to be a part of the maker community and constantly inspired by fellow artists and craftsmen. Let's chat about all things design, from mid-century modern to rustic chic! 405-753-4158",4), R.drawable.felonjail,false,"73",25478,3,10));
            productsList.add(new Product("End Workplace Discrimination for Pregnant Women","Despite existing laws, pregnant women continue to face discrimination in the workplace, from being denied reasonable accommodations to being passed over for promotions or even terminated due to their pregnancy. These discriminatory practices put women’s health at risk and prevent them from fully participating in the workforce. Every woman should have the right to work in a safe and supportive environment without fear of losing her job because she is pregnant. We must push for stronger protections that ensure pregnant women are treated fairly in the workplace. This includes mandating reasonable accommodations, protecting against retaliation, and holding employers accountable for discriminatory practices. By signing this petition, you are advocating for gender equality and the rights of working mothers, helping to create workplaces where pregnancy is not seen as a liability but as a natural part of life that deserves support and respect.","Discrimination",new User("Zack Turner","kjhgfds",R.drawable.men4,25,3.9,"Gamer by night, tech wizard by day! Whether I'm diving into the latest RPG or coding up a storm, I'm always in my element when I'm immersed in the world of technology. Proud nerd with a passion for all things sci-fi and fantasy. When I'm not conquering virtual realms or tinkering with gadgets, you can find me exploring the great outdoors or whipping up some mean BBQ on the grill. Firm believer in the power of friendship and the importance of always having a backup plan. Let's geek out over our favorite games or debate the merits of Star Trek vs. Star Wars! 405-547-1563",6), R.drawable.pregnat,false,"49",41852,15,5));
            productsList.add(new Product("Demand Equal Rights for Domestic Workers","Domestic worker face significant challenges when it comes to labor rights and protections. Many are denied basic benefits like paid leave, health insurance, and overtime pay, and they are frequently subjected to harassment and abuse. These workers are essential to the functioning of countless households, yet they remain one of the most vulnerable and underprotected labor groups. We must demand comprehensive labor protections for domestic workers, including fair wages, paid leave, health benefits, and protections against abuse and exploitation. By advocating for the rights of domestic workers, we can ensure that these individuals are treated with the dignity and respect they deserve. Sign this petition to stand up for justice and equality in the domestic labor sector, helping to create a safer and fairer environment for all workers.","Discrimination",new User("Sean Hulsey","art123",R.drawable.men12,28,4.9," Artist with a passion for capturing emotions on canvas. Whether it's a poignant portrait or a vibrant abstract, I'm always chasing the perfect expression. Inspired by the beauty of nature, I find solace and inspiration in the great outdoors.️ When I'm not painting, you can find me sketching, hiking, or savoring a cup of aromatic coffee. Proud cat parent to Mochi, the most mischievous muse you'll ever meet! Let's share artistic inspiration or plan our next gallery visit. 405-875-8879",2), R.drawable.houseclean,false,"54",12548,5,8));
            productsList.add(new Product("End Discrimination Against Disabilities in Employment", "People with disabilities face significant barriers in the workforce, from being denied job opportunities to being passed over for promotions or reasonable accommodations. Despite legal protections, many employers continue to discriminate, either consciously or unconsciously, against individuals with disabilities, limiting their ability to contribute fully to society. The unemployment rate among people with disabilities remains disproportionately high, even though many of these individuals are capable and eager to work. We must call for stronger enforcement of anti-discrimination laws and the creation of more inclusive workplaces. This includes providing necessary accommodations, addressing unconscious bias in hiring practices, and holding employers accountable when they fail to comply with the Americans with Disabilities Act (ADA). By signing this petition, you are standing up for equal employment opportunities for people with disabilities and helping to ensure that everyone has the chance to thrive in the workforce.", "Discrimination", new User("May Roberts","qwertyui",R.drawable.women2,31,4.2,"Bookworm with a love for storytelling and a passion for adventure. Whether it's getting lost in the pages of a fantasy novel or exploring new worlds through travel, I'm always seeking out new tales to inspire my own adventures. Proud explorer of both distant lands and the depths of imagination.️ When I'm not lost in a good book or planning my next getaway, you can find me indulging in my love for photography or baking up a storm in the kitchen. Firm believer in the power of kindness and spreading joy wherever I go. Let's swap book recommendations or share stories from our own travels! 405-852-9638",3), R.drawable.disabledwork,false,"22",15843,6,0 ));



            productsList.add(new Product("Increase Funding for Schools in Low-Income Areas","Educational inequity remains a major issue across the country, with schools in low-income areas often lacking the resources necessary to provide students with a high-quality education. Outdated textbooks, overcrowded classrooms, insufficient funding for extracurricular activities, and a lack of access to technology create significant disadvantages for students in these communities. Every child deserves access to the same level of education, regardless of their economic background. We must call for increased funding and investment in under-resourced schools, ensuring that all students have access to the materials, technology, and support they need to succeed. This includes smaller class sizes, up-to-date textbooks, and access to extracurricular programs that enrich student experiences. By signing this petition, you are advocating for educational equity and a fair chance for every child to reach their full potential. Let’s work together to close the opportunity gap and ensure that all students have access to a quality education.","Education", new User("Peter Rick","poiuhnm",R.drawable.men8,38,4.7,"Tech enthusiast with a passion for innovation and a knack for problem-solving. Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology.️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-897-6821",2), R.drawable.poorschool,false,"86",32625,3,0));
            productsList.add(new Product("Expand Access to Free School Meals for Low-Income Students","For many low-income families, school meals are the only consistent source of nutrition for their children. However, current programs are often underfunded, leaving many students without access to the meals they need to stay focused and healthy. No child should go hungry while trying to get an education, and expanding access to free school meals can help ensure that all students have the nutrition they need to succeed. We must demand an expansion of free school meal programs to ensure that every low-income student has access to healthy, nutritious meals during the school day. This includes increasing funding for meal programs, eliminating lunch debt, and ensuring that meals meet proper nutritional standards. By signing this petition, you are advocating for the health and well-being of students and ensuring that hunger does not stand in the way of education. Let’s work together to end childhood hunger and give every student the opportunity to thrive.","Education",new User("Alex Miller","wsedrfttg",R.drawable.men6,24,3.2,"Theatre enthusiast with a passion for bringing stories to life on stage. Whether I'm treading the boards or behind the scenes, I'm always drawn to the magic of the spotlight. Proud performer with a flair for drama and a heart full of passion. When I'm not rehearsing lines or perfecting my craft, you can find me exploring the city's hidden gems or indulging in my love for good food and great company.️ Firm believer in the power of storytelling to inspire, educate, and unite. Let's chat about our favorite plays, swap acting tips, or plan a night out at the theatre! 405-742-5556",5), R.drawable.poorkideating,false,"81",12451,5,10));
            productsList.add(new Product("Protect Arts and Music Education from Budget Cuts","As schools face budget shortfalls, arts and music programs are often the first to be cut, depriving students of opportunities for creative expression and development. Arts education is essential for fostering critical thinking, creativity, and emotional well-being, yet many students, particularly those in underfunded schools, are losing access to these programs. Every student deserves the chance to explore their artistic talents and develop a well-rounded education. We must demand that arts and music education be protected from budget cuts and that schools prioritize funding for creative programs. This includes ensuring that students have access to qualified art and music teachers, as well as the materials and resources necessary for a rich arts education. By signing this petition, you are advocating for the importance of creativity in education and standing up for students’ right to a well-rounded education. Let’s work together to ensure that the arts remain a vital part of every student’s school experience.","Education",new User("Jaren Gonzales", "ihbshb@",R.drawable.men,24,4.8,"Photographer with a passion for capturing life's beautiful moments. Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. Born and raised in the city but happiest when I'm exploring the great outdoors. When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food.️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! Let's swap photography tips or plan our next spontaneous road trip. 405-996-2365",8), R.drawable.artmusic,false,"67",22657,16,5));


            productsList.add(new Product("Abolish Private Prisons to End Profit-Driven Incarceration","The existence of private prisons allows corporations to profit from mass incarceration, creating a perverse incentive to keep people behind bars. Private prison companies cut corners on essential services like healthcare, mental health support, and rehabilitation programs to maximize profits, often resulting in dangerous and inhumane conditions for inmates. This profit-driven system also fuels mass incarceration, as companies lobby for tougher sentencing laws to keep their facilities full. We must demand the abolition of private prisons and call for the prison system to be fully operated and regulated by the government, ensuring that incarceration is focused on rehabilitation, not profit. By signing this petition, you are standing up against a corrupt system that prioritizes corporate profits over human dignity and advocating for a more just and humane criminal justice system. Let’s work together to end private prisons and build a system that values rehabilitation over punishment.","Human Rights",new User("Lanee Philip","yuioplkjhg",R.drawable.women3,52,5.0,"Photography enthusiast with a passion for capturing life's fleeting moments. Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. Proud explorer with a love for travel and a desire to see every corner of the globe. When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-698-6321",2), R.drawable.privateprison,false,"2",18452,4,0));
            productsList.add(new Product("Mandate Paid Family and Medical Leave for All Workers","The lack of paid family and medical leave in the U.S. leaves millions of workers without the support they need to care for themselves or their loved ones during times of illness, childbirth, or family emergencies. Many workers are forced to choose between taking unpaid leave or continuing to work while they or their family members are in need of care. Paid family and medical leave would provide workers with the security of knowing they can take time off when needed without sacrificing their livelihood. We must demand that Congress pass legislation mandating paid family and medical leave for all workers, ensuring that no one is forced to choose between their job and their family’s well-being. This includes providing a minimum of 12 weeks of paid leave for medical emergencies, childbirth, and caregiving responsibilities. By signing this petition, you are advocating for workers' rights and helping to create a more compassionate and supportive society. Let’s work together to ensure that every worker has access to paid leave when they need it most.","Human Rights",new User("Lanee Philip","yuioplkjhg",R.drawable.women3,52,5.0,"Photography enthusiast with a passion for capturing life's fleeting moments. Whether I'm chasing sunsets or documenting candid smiles, I'm always on the lookout for beauty in the world around me. Proud explorer with a love for travel and a desire to see every corner of the globe. When I'm not behind the lens, you can find me hiking through nature trails or immersing myself in a good book at a cozy café. Firm believer in the power of connection and the ability of photographs to tell stories that transcend language barriers. Let's share our favorite travel destinations, swap photography tips, or embark on an adventure together! 405-865-9638",2), R.drawable.paidfamily,false,"17",45412,9,0));


            productsList.add(new Product("Implement a Carbon Tax to Combat Climate Change","Climate change is one of the most pressing issues of our time, with rising temperatures, extreme weather events, and the loss of biodiversity threatening communities around the world. Fossil fuel emissions are the leading cause of climate change, yet industries continue to pollute without paying for the damage they cause. A carbon tax would incentivize companies to reduce their carbon emissions by making them financially accountable for their environmental impact. We must demand the implementation of a carbon tax to hold polluters accountable and accelerate the transition to clean energy. Revenue from the carbon tax can be reinvested in renewable energy projects, public transportation, and climate adaptation measures, ensuring a sustainable and equitable future. By signing this petition, you are advocating for bold action on climate change and supporting policies that prioritize the health of our planet. Let’s work together to combat climate change and create a greener future for all.","Environment",new User("Jaren Gonzales", "ihbshb@",R.drawable.men,24,4.8,"Photographer with a passion for capturing life's beautiful moments. Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. Born and raised in the city but happiest when I'm exploring the great outdoors.️ When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food.️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! Let's swap photography tips or plan our next spontaneous road trip. 405-895-6677",8), R.drawable.carbontax,false,"78",49562,16,5));
            productsList.add(new Product("Pass Laws to Promote Food Recovery Programs","In a world where millions go hungry, it is unacceptable that nearly one-third of all food produced is wasted. Food waste contributes to environmental degradation, with wasted food often ending up in landfills, producing harmful greenhouse gases. At the same time, many people struggle with food insecurity, unable to access the nutritious meals they need. We must demand the passage of laws that reduce food waste by promoting food recovery programs, encouraging businesses to donate surplus food, and implementing composting initiatives. By signing this petition, you are advocating for a more sustainable and equitable food system that ensures everyone has access to the food they need. Let’s work together to eliminate food waste and create a more just and sustainable world for all.","Environment",new User("Piper Woodard","poiuyhbnmjuygf",R.drawable.women5,19,4.8,"Nature enthusiast with a heart full of wanderlust and a soul that craves adventure. Whether I'm hiking through lush forests or camping under the stars, I'm always happiest when surrounded by the beauty of the great outdoors.️ Proud environmentalist with a passion for sustainability and a love for all creatures big and small. When I'm not exploring Mother Nature's wonders, you can find me curled up with a good book or experimenting with plant-based recipes in the kitchen. Firm believer in the power of connection and the importance of living in harmony with the Earth. Let's swap hiking stories, share tips for reducing our carbon footprint, or plan our next eco-friendly adventure! 405-321-6952",12), R.drawable.food,false,"14",39542,7,0));
//            productsList.add(new Product("Education Workshop","Soar through the treetops and experience the thrill of zip-lining as you embark on an unforgettable adventure high above the ground. Strap on your harness, step onto the platform, and take a deep breath as you prepare to launch into the air and zip along exhilarating zip lines suspended between towering trees and rugged terrain. Feel the wind rushing past your face as you fly through the canopy, taking in panoramic views of the surrounding landscape below. Whether you're gliding over dense forests, cascading waterfalls, or lush valleys, zip-lining offers an adrenaline-pumping experience that will leave you feeling exhilarated and alive. So join me, and let's zip through the air together on an adventure that will take your breath away!","Homestead Ziplines", new User("PeterRick","poiuhnm",R.drawable.men8,38,4.7,"\uD83D\uDE80 Tech enthusiast with a passion for innovation and a knack for problem-solving. \uD83D\uDCA1 Whether I'm coding late into the night or brainstorming the next big idea, I'm always on the cutting edge of technology. \uD83D\uDDA5️ Proud geek with a love for all things sci-fi and a collection of gadgets that would make even Tony Stark jealous. \uD83C\uDF0C When I'm not immersed in the digital realm, you can find me exploring the great outdoors or whipping up some delicious dishes in the kitchen. \uD83C\uDF73 Firm believer in the power of technology to shape a better future and make the impossible possible. Let's chat about the latest tech trends, swap coding tips, or plan our next intergalactic adventure! 405-333-5279",2),R.drawable.zipline,false,"64",24513,6,10));
//            productsList.add(new Product("Wildlife Conservation","Welcome to our Science Fair, a vibrant celebration of discovery and innovation that ignites the imagination and fuels the spirit of inquiry. As you enter our bustling exhibition hall, you'll find yourself immersed in a kaleidoscope of scientific wonder, where each project represents a journey of exploration and experimentation. From the intricacies of biology to the marvels of physics and beyond, our fair showcases the boundless potential of scientific inquiry. Engage with passionate participants as they present their findings, embark on interactive demonstrations, and delve into thought-provoking discussions. Amidst the buzz of excitement and the hum of intellectual curiosity, let us inspire and be inspired by the limitless possibilities of science.","Sunville Elementary",new User("TommyParker","science123",R.drawable.men10,32,4.9,"\uD83C\uDFB5 Musician with a passion for composing melodies that stir the soul. \uD83C\uDFB6 Whether it's a haunting piano piece or an upbeat guitar riff, I'm always chasing the perfect harmony. \uD83C\uDF0C Inspired by the cosmos, I find inspiration in the depths of the night sky. \uD83C\uDFB8 When I'm not lost in the rhythm, you can find me stargazing, jamming with friends, or experimenting with new recipes in the kitchen. \uD83D\uDC36 Proud goldfish parent to Bubbles, the most mesmerizing swimmer you'll ever meet! \uD83D\uDC1F Let's swap musical notes or plan our next impromptu jam session. \uD83C\uDFBC #MusicMaker #Stargazer #KitchenMaestro 405-324-4171",5),R.drawable.science,false,"74",49813,10,0));
//            productsList.add(new Product("Senior Citizen Activity Center","Welcome to our Trivia Night, where knowledge reigns supreme and fun knows no bounds. As you enter our lively venue, prepare to immerse yourself in an evening of brain-teasing challenges and friendly competition. Our experienced hosts will guide you through an array of intriguing trivia questions spanning a multitude of topics, ensuring a thrilling experience for participants of all backgrounds. But Trivia Night is more than just a test of wits; it's an opportunity to connect with friends, old and new, as you collaborate to uncover obscure facts and share in the excitement of victory. Join us for an unforgettable evening filled with laughter, camaraderie, and the thrill of triumphing over trivia.","Starbucks",new User("AlexMiller","trivia123",R.drawable.men11,27,4.7,"\uD83D\uDCDA Writer with a passion for crafting stories that resonate with the human experience. ✨ Whether it's a heartfelt romance or an epic adventure, I'm always chasing the perfect narrative. \uD83C\uDFD9️ Raised in the hustle and bustle of the city, but my imagination thrives in quiet moments of reflection. \uD83D\uDD8B️ When I'm not lost in the world of words, you can find me exploring hidden bookstores or indulging in my love for dark chocolate. \uD83D\uDCD6 Proud plant parent to Basil, the most tenacious little sprout you'll ever meet! \uD83C\uDF31 Let's share writing prompts or plan our next literary escapade. \uD83D\uDCDD #Storyteller #PlantParent #Bookworm 405123-6652",4),R.drawable.trivia,false,"7",42518,8,8));
//            productsList.add(new Product("New Soup Kitchen","Welcome to the Soup Kitchen, where warmth and compassion await. Step into our humble space, where every bowl served is a gesture of kindness towards those in need. Savor the simple yet hearty flavors of our soups, crafted with care from the freshest ingredients available. Each spoonful not only fills the stomach but also warms the soul, reminding us of the power of generosity and empathy. But our Soup Kitchen Gathering is more than just a meal; it's a beacon of hope and solidarity. Take a seat at our communal table and engage in conversations that transcend boundaries, sharing stories and experiences that enrich us all. Together, we can create a ripple of positive change, one bowl at a time. Join us for a day filled with warmth, nourishment, and the knowledge that each bowl served brings us closer together.","Miami Soup Kitchen",new User("NathanHale","volunteer123",R.drawable.men13,29,4.8,"\uD83C\uDF99️ Podcaster with a passion for sparking meaningful conversations and exploring diverse perspectives. \uD83C\uDFA7 Whether it's a thought-provoking interview or a lighthearted discussion, I'm always chasing the perfect dialogue. \uD83C\uDF0D Driven by a curiosity about the world, I find inspiration in the stories of everyday people. \uD83D\uDCDA When I'm not recording episodes, you can find me browsing antique markets, volunteering at local shelters, or enjoying a leisurely bike ride. \uD83D\uDC31 Proud cat parent to Whiskers, the most inquisitive feline friend you'll ever meet! \uD83D\uDC3E Let's share podcasting insights or plan our next community event. \uD83C\uDFA4 #PodcastHost #CatParent #CommunityBuilder 405-547-6326",7),R.drawable.soup,false,"24",489,15,0));
//            productsList.add(new Product("Community Sport League", "Let's escape the hustle and bustle of everyday life and venture into the serene wilderness together. Feel the thrill of discovery as we traverse winding trails, surrounded by towering trees and breathtaking vistas. With each step, we'll share stories, laughter, and the joy of exploring nature's hidden treasures. Let's breathe in the crisp mountain air, listen to the symphony of birdsong, and immerse ourselves in the beauty of the great outdoors. Whether you're an experienced hiker or just starting out, there's something magical about embarking on this journey with friends by your side. So lace up your hiking boots, pack your water bottles, and join me as we embark on an unforgettable adventure into the heart of nature.", "Destin Nature Park", new User("JarenGonzales", "ihbshb@",R.drawable.men,24,4.8,"\uD83D\uDCF8 Photographer with a passion for capturing life's beautiful moments. \uD83C\uDF1F Whether it's a breathtaking landscape or candid smiles, I'm always chasing the perfect shot. \uD83D\uDCF7 Born and raised in the city but happiest when I'm exploring the great outdoors. \uD83C\uDFDE️ When I'm not behind the lens, you can find me hiking, camping, or indulging in my love for spicy food. \uD83C\uDF36️ Proud dog dad to Luna, the fluffiest adventure buddy you'll ever meet! \uD83D\uDC3E Let's swap photography tips or plan our next spontaneous road trip. \uD83D\uDE0A #Wanderlust #DogDad #AdventureSeeker 405-687-2145",8), R.drawable.park,true,"51",19745,7,0));

            int temp;
        Product temp2;
        Product temp3;
//            for(int x = 0; x < productsList.size();x++){
//                temp = (int)(Math.random()* (productsList.size()-1));
//                temp2 = productsList.get(temp);
//                productsList.set(temp,productsList.get(x));
//                productsList.set(x,temp2);
//            }

            ForYouActivity.setFirst(false);
        }

        ProductAdapter adapter = new ProductAdapter(this);
        adapter.setProducts(productsList);
        products.setAdapter(adapter);
        products.setLayoutManager(new GridLayoutManager(this,1));


    }
    public void openMainActivity(){

        Intent intent = new Intent(this, MainActivity2.class);
        this.startActivity(intent);
    }
    public void openInboxActivity(){

        Intent intent = new Intent(this, InboxActivity.class);
        this.startActivity(intent);
    }
    public void openProfileActivity(){

        Intent intent = new Intent(this, ProfileActivity.class);
        this.startActivity(intent);
    }
    public void openForYouActivity(){

        Intent intent = new Intent(this, ForYouActivity.class);
        this.startActivity(intent);
    }
    public void openFollowingActivity(){

        Intent intent = new Intent(this, FollowingActivity.class);
        this.startActivity(intent);
    }

    public void openSearchActivity(){

        Intent intent = new Intent(this, SearchActivity.class);
        this.startActivity(intent);
    }
    public void openUserPage(){
        Intent intent = new Intent(getApplicationContext(), UserPage.class);
        getApplicationContext().startActivity(intent);
    }
    public static Product findProduct(String name){

        for(int x = 0; x < productsList.size();x++){
            if(productsList.get(x).getProductName().equals(name)){
                return productsList.get(x);
            }
        }
        return null;
    }
    public static boolean findProductInForYouBoolean(String name, String image){

        for(int x = 0; x < ForYouActivity.getForYouList().size();x++){
            if(ForYouActivity.getForYouList().get(x).getProductName().equals(name) && ForYouActivity.getForYouList().get(x).getProductImageURL().equals(image)){
                return true;
            }
        }
        return false;
    }
    public static boolean findProductInFollowingBoolean(String name, String image){

        for(int x = 0; x < FollowingActivity.getFollowingProductList().size();x++){
            if(FollowingActivity.getFollowingProductList().get(x).getProductName().equals(name) && FollowingActivity.getFollowingProductList().get(x).getProductImageURL().equals(image)){
                return true;
            }
        }
        return false;
    }
    public static ArrayList<Product> getProductsList(){
        return productsList;
    }

    public static void addToProdList(Product forNow){
        productsList.add(forNow);
    }


}